from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel
from typing import Optional
import pandas as pd
import os

app = FastAPI(title="Dubai Real Estate Yield API")

# Configuration: Path to the CSV generated by your main.py pipeline
DATA_FILE = 'dubai_market_yield_report.csv'

def load_data():
    if not os.path.exists(DATA_FILE):
        return pd.DataFrame()
    return pd.read_csv(DATA_FILE)

# Pydantic model for ROI Calculation inputs
class ROIRequest(BaseModel):
    area_name: str
    room_id: int
    year: int = 2026
    custom_annual_rent: Optional[float] = None  # User can define their own rent

@app.get("/filter")
async def filter_data(
    area: Optional[str] = None,
    room_id: Optional[int] = None,
    year: Optional[int] = 2026
):
    """
    General filtering endpoint to get market stats for an area/room.
    """
    df = load_data()
    if df.empty:
        raise HTTPException(status_code=503, detail="Data file not found. Run main.py first.")

    query = df.copy()
    if area:
        query = query[query['area_name_en'].str.contains(area, case=False, na=False)]
    if room_id is not None:
        query = query[query['room_id'] == room_id]
    if year:
        query = query[query['year'] == year]

    return query.to_dict(orient="records")

@app.post("/calculate_roi")
async def get_roi(request: ROIRequest):
    """
    Calculates ROI/Yield. 
    If custom_annual_rent is provided, it uses that.
    Otherwise, it defaults to the market median_annual_rent.
    """
    df = load_data()
    
    # Locate specific market row
    match = df[
        (df['area_name_en'].str.lower() == request.area_name.lower()) & 
        (df['room_id'] == request.room_id) & 
        (df['year'] == request.year)
    ]

    if match.empty:
        raise HTTPException(status_code=404, detail="No market data found for this area/room combo.")

    row = match.iloc[0]
    transaction_price = row['median_transaction_amount']
    
    # Use Custom Rent if provided, else use Median
    final_rent = request.custom_annual_rent if request.custom_annual_rent else row['median_annual_rent']
    
    # Calculate Yield (ROI)
    calculated_yield = (final_rent / transaction_price) * 100

    return {
        "area": row['area_name_en'],
        "rooms": row['rooms_en'],
        "year": int(row['year']),
        "input_used": "Custom Rent" if request.custom_annual_rent else "Market Median",
        "annual_amount_used": final_rent,
        "market_median_price": transaction_price,
        "roi_yield_percentage": round(calculated_yield, 2),
        "market_bounds": {
            "min_rent": row['min_annual_rent'],
            "max_rent": row['max_annual_rent']
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)